- alias: 'Car movement alert'
  trigger:
     platform: state
     entity_id: device_tracker.kiaceed_tracker
  condition:
     condition: template
     value_template: '{{ trigger.from_state!=None and distance( trigger.from_state,  trigger.to_state ) >= 1.0 }}'
  action:
    service: script.car_location_notify


- alias: 'Update available notification'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: mqtt.publish
    data:
      topic: '/home/notify'
      payload_template: 'Update for Home Assistant is available.'
      retain: False