- platform: mjpeg
  mjpeg_url: http://127.0.0.1:8081/
  name: Front door

- platform: generic
  name: Locations
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.kiaceed_tracker.attributes.latitude }},{{ states.device_tracker.kiaceed_tracker.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:C%7C{{ states.device_tracker.kiaceed_tracker.attributes.latitude }},{{ states.device_tracker.kiaceed_tracker.attributes.longitude }}
  limit_refetch_to_url_change: true

- platform: mqtt
  name: Last motion
  topic: /home/camera/door/photo

- platform: local_file
  name: Last track
  file_path: /home/hub/services/lasttrack.png

- platform: ffmpeg
  name: Last video
  input: /home/hub/motion/lastmotion.mp4

#- platform: ffmpeg
#  name: Indoor
#  input: /dev/video1 
