homeassistant:
  name: Home
  latitude: !secret zone_home_lat
  longitude: !secret zone_home_lon

  elevation: 25
  unit_system: metric
  time_zone: Europe/Moscow
  customize: !include customize.yaml

recorder:
  purge_interval: 1
  purge_keep_days: 5
  exclude:
    domains:
      - automation
      - weblink
      - camera
    entities:
      - sun.sun
      - sensor.time
      - sensor.energy
      - sensor.hot_water
      - sensor.cold_water
      - sensor.car_last_distance
      - sensor.car_activity
      - sensor.energy_day_counter
      - sensor.energy_night_counter

history:
  exclude:
    domains:
      - camera
      - sun

zone: !include zones.yaml

logger:
  default: error

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # url_prefix: /home

#shopping_list:

# Checks for available updates
updater:
  reporting: False

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# View all events in a logbook
logbook:

# Track the sun
sun:

map:

telegram_bot: !include telegram.yaml

automation: !include automation.yaml

mqtt:
  broker: 127.0.0.1
  username: !secret mqtt_username
  password: !secret mqtt_password

notify: !include notify.yaml

sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
camera: !include cameras.yaml
media_player: !include media_players.yaml

weather:
  - platform: openweathermap
    name: weather
    api_key: !secret openweathermap_key

device_tracker: !include device_tracker.yaml
rest_command: !include rest.yaml
group: !include groups.yaml
script: !include scripts.yaml

#android_ip_webcam:
#   - host: 192.168.168.101
#     port: 8080

# Text to speech
#tts:
#  platform: google
